#!/bin/bash
#SBATCH --job-name=train-job             # Job name

#SBATCH --account=peichi1                   # Replace with your netid
#SBATCH --partition=gpu                   # Partition name (default is gpu)
#SBATCH --nodes=1                         # One node (tomago/tempura)
#SBATCH --ntasks-per-node=1               # Number of CPU cores (vary it as needed)
#SBATCH --mem=16G                         # Memory per node
#SBATCH --gpus=1                          # Number of GPUs (for HW1, let it be 1)
#SBATCH --time=02:00:00                   # Max runtime = 2 hours (cluster limit)

#SBATCH --chdir=/homes/iws/peichi1/courses/599o/assignment1-basics/cse599o_basics  # Working directory
#SBATCH --export=ALL                      # Export environment variables
#SBATCH --output=peichi1-slurm-%j.out             # STDOUT log file (%j = JobID)
#SBATCH --error=peichi1-slurm-%j.err              # STDERR log file (%j = JobID)

# --- Example Command to run ---
srun uv run pytest